[package]
name = "delta-v-assets"
version.workspace = true
edition = "2024"
description = "Asset loading and template management for the delta-v game"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["gamedev", "spacesim", "assets"]
categories = ["game-development"]

[dependencies]
serde_json = { workspace = true }
bevy = { workspace = true }
delta-v-json = { workspace = true }
delta-v-types = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
