[package]
name = "delta-v-spawn"
version.workspace = true
edition = "2024"
description = "Spawning utilities for the delta-v game"
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["gamedev", "spacesim", "spawning"]
categories = ["game-development"]

[dependencies]
serde_json = { workspace = true }
bevy = { workspace = true }
delta-v-types = { workspace = true }
delta-v-json = { workspace = true }
delta-v-assets = { workspace = true }
delta-v-core = { workspace = true }
delta-v-physics = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
